version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env.local

    volumes:
     - ".:/code:rw"
     - "./data:/data:rw"
    ports:
      - "8000:8000"
    depends_on:
      - db
